version: '3.8'
services:
  php:
    build: ./
    volumes:
      - ${DEV_PATCH}:/var/www/html
    ports:
      - "80:80"
    environment:
      - "APACHE_MOD_REWRITE=${APACHE_MOD_REWRITE}"  # Utilizando a variável de ambiente APACHE_MOD_REWRITE
    command: bash -c "a2enmod rewrite && docker-php-entrypoint apache2-foreground"
    networks:
      - php_network
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # Utilizando a variável de ambiente MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: ${MYSQL_DATABASE}             # Utilizando a variável de ambiente MYSQL_DATABASE
      MYSQL_USER: ${MYSQL_USER}                     # Utilizando a variável de ambiente MYSQL_USER
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}             # Utilizando a variável de ambiente MYSQL_PASSWORD
    volumes:
      - ~/data/mysql_data_php8.2:/var/lib/mysql
    networks:
      - php_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - php_network
networks:
  php_network:
    driver: bridge
volumes:
  mysql_data_php8.2:
